popservername = 'pop.secureserver.net'
popusername   = 'PP4E@learning-python.com'
smtpservername = 'smtpout.secureserver.net'
myaddress   = 'PP4E@learning-python.com'
mysignature = ('Thanks,\n--Mark Lutz  (http://learning-python.com, http://rmi.net/~lutz)')
smtpuser  = None
smtppasswdfile  = ''
poppasswdfile  = r'c:\temp\pymailgui.txt'
sentmailfile   = r'.\sentmail.txt'
savemailfile   = r'c:\temp\savemail.txt'
fetchEncoding = 'utf8'
headersEncodeTo = None
fetchlimit = 25            